import Navbar from '@/components/navbar';
import './globals.css';
import { Mukta } from 'next/font/google';

const inter = Mukta({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        {children}
        <footer>test footer</footer>
      </body>
    </html>
  );
}
